// The Cloudflare config under dist/ is regenerated by every build, so the two
// addresses the site answers on cannot live in it. They live here, and this
// runs between `vinext build` and `wrangler deploy` — which is why `npm run
// deploy` is one command rather than a build plus a remembered dashboard click.
//
// `custom_domain: true` makes Cloudflare create the DNS record and the
// certificate itself. It is the same mechanism `Service/wrangler.toml` uses for
// api.witnessmac.com, and it means there is no A record to keep in agreement
// with anything.
import { readFileSync, writeFileSync } from "node:fs";

const CONFIG = "dist/server/wrangler.json";
const DOMAINS = ["witnessmac.com", "www.witnessmac.com"];

const config = JSON.parse(readFileSync(CONFIG, "utf8"));
config.routes = DOMAINS.map((pattern) => ({ pattern, custom_domain: true }));
writeFileSync(CONFIG, `${JSON.stringify(config, null, 2)}\n`);

console.log(`${CONFIG}: ${DOMAINS.join(", ")}`);
