// The Cloudflare config under dist/ is regenerated by every build, so what the
// deployment needs beyond the code cannot live in it. It lives here, and this
// runs between `vinext build` and `wrangler deploy` — which is why `npm run
// deploy` is one command rather than a build plus a remembered dashboard click.
//
// `custom_domain: true` makes Cloudflare create the DNS record and the
// certificate itself. It is the same mechanism `Service/wrangler.toml` uses for
// api.witnessmac.com, and it means there is no A record to keep in agreement
// with anything.
//
// DOWNLOAD_URL is a var rather than a secret because it is a public address,
// and it is in source control rather than in the dashboard because a download
// button that quietly falls back to "private preview" looks exactly like a
// download button that works. `app/_lib/download.ts` validates it again at
// runtime and refuses anything that is not plain HTTPS.
import { readFileSync, writeFileSync } from "node:fs";

const CONFIG = "dist/server/wrangler.json";
const DOMAINS = ["witnessmac.com", "www.witnessmac.com"];
const VARS = {
  // `latest` and a version-neutral file name, so shipping 0.2.0 needs neither
  // an edit here nor a deploy of this site. The release asset has to keep being
  // called Witness.dmg for that to hold; `docs/PHASE_6_RELEASE.md` says so
  // where somebody cutting a release will read it.
  DOWNLOAD_URL: "https://github.com/igskak/localdictation/releases/latest/download/Witness.dmg",

  // Measurement for the paid-search campaign in `docs/GTM.md`. Vars rather
  // than secrets, and here rather than in a dashboard, for the same reason as
  // the line above: all three ship to the browser inside the tag, so none of
  // them is a secret, and a measurement that silently stopped after a deploy
  // looks exactly like a campaign that stopped working. Paste the three
  // identifiers from the Google Ads and Analytics accounts and deploy; until
  // then the site loads no tag and both privacy policies say so.
  GA4_MEASUREMENT_ID: "G-CWNBL1TC3B",
  ADS_CONVERSION_ID: "AW-18439722393",
  // Nothing receives a lead today (`LEAD_ENDPOINT` is unset and the service has
  // no route for one), so this label reports nothing until that is built. It
  // stays here because the conversion action exists and will be needed.
  ADS_LEAD_CONVERSION_LABEL: "8apHCIq59vEcEJmr39hE",
  // Reaching the download page. Observation only -- never a bidding target.
  // ADS_DOWNLOAD_CONVERSION_LABEL: "XXXXXXXXXXXXXXXXXXX",
};

const config = JSON.parse(readFileSync(CONFIG, "utf8"));
config.routes = DOMAINS.map((pattern) => ({ pattern, custom_domain: true }));
config.vars = { ...config.vars, ...VARS };
writeFileSync(CONFIG, `${JSON.stringify(config, null, 2)}\n`);

console.log(`${CONFIG}: ${DOMAINS.join(", ")}`);
for (const [name, value] of Object.entries(VARS)) console.log(`  ${name} = ${value}`);
