// The Cloudflare config under dist/ is regenerated by every build, so what the
// deployment needs beyond the code cannot live in it. It lives here, and this
// runs between `vinext build` and `wrangler deploy` — which is why `npm run
// deploy` is one command rather than a build plus a remembered dashboard click.
//
// `custom_domain: true` makes Cloudflare create the DNS record and the
// certificate itself. It is the same mechanism `Service/wrangler.toml` uses for
// api.witnessmac.com, and it means there is no A record to keep in agreement
// with anything.
//
// DOWNLOAD_URL is a var rather than a secret because it is a public address,
// and it is in source control rather than in the dashboard because a download
// button that quietly falls back to "private preview" looks exactly like a
// download button that works. `app/_lib/download.ts` validates it again at
// runtime and refuses anything that is not plain HTTPS.
import { readFileSync, writeFileSync } from "node:fs";

const CONFIG = "dist/server/wrangler.json";
const DOMAINS = ["witnessmac.com", "www.witnessmac.com"];
const VARS = {
  DOWNLOAD_URL: "https://github.com/igskak/localdictation/releases/download/v0.1.0/Witness-0.1.0.dmg",
};

const config = JSON.parse(readFileSync(CONFIG, "utf8"));
config.routes = DOMAINS.map((pattern) => ({ pattern, custom_domain: true }));
config.vars = { ...config.vars, ...VARS };
writeFileSync(CONFIG, `${JSON.stringify(config, null, 2)}\n`);

console.log(`${CONFIG}: ${DOMAINS.join(", ")}`);
for (const [name, value] of Object.entries(VARS)) console.log(`  ${name} = ${value}`);
